Cria a tela de Feedback
tryber/sd-013-a-project-trivia-react-redux pull request #40
Opened 2021-09-02 20:59 UTC by walacenascimento

2021-09-02 21:03 UTC, thomasravache approved these changes
Boa!

2021-09-02 21:16 UTC, Fraitz requested changes

2021-09-02 21:16 UTC, Fraitz commented on src/pages/Feedbacks.js
> +            <input
Tente componentizar o `Header`, nesta tela não tem nenhum input,

2021-09-02 22:27 UTC, AndreLeme approved these changes
boa

2021-09-03 16:42 UTC, AndreLeme commented
> agora que reparei melhor, cade o componente Header? Está faltando o arquivo dele (_Header.js_ dentro da pasta _components_), a importação desse arquivo na página feedback e utilização do componente Header propriamente dito.

2021-09-03 16:43 UTC, AndreLeme requested changes
agora que reparei melhor, cade o componente Header? Está faltando o arquivo dele (_Header.js_ dentro da pasta _components_), a importação desse arquivo na página feedback e utilização do componente Header propriamente dito.
Qualquer coisa a gente se ajuda pra fazer!

2021-09-03 17:50 UTC, thomasravache commented on src/pages/Feedbacks.js
> +export default Feedbacks;
```suggestion
import React, { Component } from 'react';
import Header from '../components/Header';

class Feedbacks extends Component {
  render() {
    return (
      <div>
         <Header  />
      </div>
    );
  }
}

export default Feedbacks;
```

2021-09-03 18:44 UTC, thomasravache approved these changes
Gostei!

2021-09-03 18:45 UTC, AndreLeme approved these changes
maravilha alberto!

2021-09-03 18:45 UTC, merged